services:
  neo4j:
    image: neo4j:5.17.0-enterprise
    volumes:
      - graph_data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 8290:7474
      - 8291:7687
    networks:
      - vaults_services_network
  graph_kb_service:
    build: graph_kb_service
    volumes:
      - ./graph_kb_service:/usr/src/graph_kb_service
    env_file:
      - ./graph_kb_service/.env
    depends_on:
      - neo4j
    ports:
      - 8210:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_kb_service/uvicorn_logging.conf"
    networks:
      - vaults_services_network
  graph_rag_service:
    build: graph_rag_service
    volumes:
      - ./graph_rag_service:/usr/src/graph_rag_service
    env_file:
      - ./graph_rag_service/.env
    depends_on:
      - neo4j
    ports:
      - 8500:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_rag_service/uvicorn_logging.conf"
    networks:
      - graph_rag_service_network
      - vaults_services_network
      - papper-backend

volumes:
  graph_data:


networks:
  vaults_services_network:
    name: vaults_services_network
  graph_rag_service_network:
    name: graph_rag_service_network
  papper-backend:
    name: papper-backend
    external: true
