services:
  papper-neo4j:
    image: neo4j:5.17.0-enterprise
    container_name: papper-neo4j
    restart: unless-stopped
    volumes:
      - papper-neo4j-volume:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 8290:7474
      - 8291:7687
    networks:
      - papper-vaults-service-network
  papper-graph-kb-service:
    build: graph_kb_service
    container_name: papper-graph-kb-service
    restart: unless-stopped
    volumes:
      - ./graph_kb_service:/usr/src/graph_kb_service
    env_file:
      - ./graph_kb_service/.env
    depends_on:
      - papper-neo4j
    ports:
      - 8210:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_kb_service/uvicorn_logging.conf"
    networks:
      - papper-vaults-service-network
  papper-graph-rag-service:
    build: graph_rag_service
    container_name: papper-graph-rag-service
    restart: unless-stopped
    volumes:
      - ./graph_rag_service:/usr/src/graph_rag_service
    env_file:
      - ./graph_rag_service/.env
    depends_on:
      - papper-neo4j
    ports:
      - 8500:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_rag_service/uvicorn_logging.conf"
    networks:
      - papper-graph-rag-service-network
      - papper-vaults-service-network
      - papper-backend

volumes:
  papper-neo4j-volume:

networks:
  papper-vaults-service-network:
    name: papper-vaults-service-network
  papper-graph-rag-service-network:
    name: papper-graph-rag-service-network
  papper-backend:
    name: papper-backend
    external: true
